let theUsername = "";

const ani = document.querySelectorAll(".highway, .city, .wheel img");
const playButtonElement = document.getElementById("play_button");
if(playButtonElement) {

  playButtonElement.addEventListener('click', async function() {

/**
 * This event listener handles the click event on the play button.
 * It retrieves the username input value, validates it, and stores it in local storage.
 * If the username is valid (not empty), it redirects the user to "combined.html".
 * If the username is empty, it displays an alert asking the user to enter a username.
 *
 * @param {Event} event - The event object generated by the button click.
 */

    const username = document.getElementById('username').value.trim();
    // Check if username is not empty
  if (username !== '') {
      theUsername = username;
      localStorage.setItem('username', theUsername); 
      window.location.href = "combined.html";
    }

    else {
      alert('Please enter a username.');
    }

  });
}
// Retrieve username from localStorage
theUsername = localStorage.getItem('username');
/**
 * Displays the given username on the page.
 *
 * @param {string} username - The username to display.
 */
function displayUsername(username) {
  const usernameDisplayElement = document.getElementById('username_display');
  if (usernameDisplayElement) {
    usernameDisplayElement.innerHTML = `Username: ${username}`;
  }
}

// Car animation control
const car = document.querySelector('.car');
const highway = document.querySelector('.highway');
const city = document.querySelector('.city');

let carAnimationId;
let highwayAnimationId;
let cityAnimationId;
let quizTimer;
let currentQuestion = 1;
let timer;
let timeLeft = 15;
let score = 0;

// Function to start the car animation
function startCarAnimation() {
  carAnimationId = requestAnimationFrame(startCarAnimation);
}

// Function to start the highway animation
function startHighwayAnimation() {
  highwayAnimationId = requestAnimationFrame(startHighwayAnimation);
}

// Function to start the city animation
function startCityAnimation() {
  cityAnimationId = requestAnimationFrame(startCityAnimation);
}

/**
 * Starts the timer for the quiz.
 * Sets up an interval to display quiz questions at regular intervals.
 */
function startQuizTimer() {
    // Set a timeout to stop the animations after 10 seconds
    quizTimer = setInterval(displayQuizQuestion, 10000); // Display quiz question every 10 seconds
  }
 
/**
 * Displays a quiz question on the page.
 * Clears the previous quiz timer to prevent multiple questions from displaying simultaneously.
 */

function displayQuizQuestion() {

  clearInterval(quizTimer);
  const quizContainer = document.getElementById('quiz-container');
  quizContainer.style.display = 'block'; 

  //Pauses the animation when the question box shows up
  ani.forEach(e => {
    e.classList.add('paused-animation');
  });

  startTimer(); // Start the timer for the current question
}

/**
 * Starts the countdown timer for each quiz question.
 * Updates the displayed time remaining and triggers the next question when time runs out.
 */
function startTimer() {
  function updateTimer() {
    document.getElementById('time-left').innerText = timeLeft;
    timeLeft--;

    if (timeLeft < 0) {
      clearInterval(timer);
      timeLeft = 0;
      nextQuestion();
    }
  }

  updateTimer();
  timer = setInterval(updateTimer, 1000);
}


/**
 * Handles moving to the next quiz question.
 * Checks the user's answer, updates the score, and displays the next question or final score.
 */

function nextQuestion() {
    const container = document.getElementById('quiz-container');
    const currentQuestionElement = document.getElementById(`question${currentQuestion}`);
  
    const selectedAnswer = document.querySelector(`input[name="q${currentQuestion}"]:checked`);
    const answer = selectedAnswer ? selectedAnswer.value : ''; // If no answer selected, assign empty string
  
    // Checking answer & updating score
    if (currentQuestion === 1 && answer === 'a') {
      score++;
    }
    if (currentQuestion === 2 && answer === 'b') {
      score++;
    }
  
    // Hide current question and show score after answering all questions
    if (currentQuestion === 2) {
      clearInterval(timer);
      currentQuestionElement.style.display = 'none';
      document.getElementById('score').style.display = 'block';
      document.getElementById('score-result').innerText = `Your score is: ${score}/2`;
  
      document.getElementById('next-btn').style.display = 'none';
      
      //Only let the car move if the player answers all the questions right
      //Make sure to change the '2' to however many questions there are
      if(score === 2){
        ani.forEach(e => {
          e.classList.remove('paused-animation');
        });
      }
      return;
    }

    // Hide current question
    currentQuestionElement.style.display = 'none';
  
    currentQuestion++;
    const nextQuestionElement = document.getElementById(`question${currentQuestion}`);
    nextQuestionElement.style.display = 'block';
  
    // Reset timer and start for the next question
    clearInterval(timer);
    timeLeft = 15;
    startTimer();
  }



// Event listener to initialize animations and quiz timer when the page loads
window.addEventListener('load', () => {
  displayUsername(theUsername);
  startCarAnimation();
  startHighwayAnimation();
  startCityAnimation();
  startQuizTimer();
});
