/**
 * The tutorial button is being set up by using the HTML id.
 * @type {HTMLElement}
 */

const tutorialButton = document.getElementById("tutorial_button");

/**
 * The tutorial button is supposed to direct the user to a set of instructions on how
 * to navigate the game. Using the addEventListen function, the How To Play button is
 * being set up. When the user clicks on the button, they can see the instructions in
 * front of them, and once they are done reading those instructions, the user will click
 * on the button again to go back to the main menu, where the user can choose from other
 * available options.
 *
 * @param {Event} event - The event object generated by the button click.
 */
tutorialButton.addEventListener("click", function(){
    if(!document.getElementById("tutorial-box")){
        const textBox = document.createElement("div");
        const h1 = document.createElement("h1");
        const p = document.createElement("p");
        const p1 = document.createElement("p");
        const p2 = document.createElement("p");

        h1.innerHTML = "How To Play";
        p.innerHTML = "Welcome! This game is designed to help you learn more about the rules of the road.";
        p1.innerHTML = "To get started, press the 'PLAY!' button. Once you are in the game, a series of questions will pop up. Answer these questions within the given time limit to test your mastery of the road. At the end of the level, you will see how well you did. Aim to get 70% of the questions right to pass the test.";
        p2.innerHTML = "To close this menu, reclick the 'How to play' button.";
        textBox.setAttribute("id", "tutorial-box");
        p.setAttribute("class", "instruction-paragraph");
        p1.setAttribute("class", "instruction-paragraph");
        p2.setAttribute("class", "instruction-paragraph");

        const instructions = document.getElementById("tutorial-text");
        instructions.appendChild(textBox);
        textBox.appendChild(h1);
        textBox.appendChild(p);
        textBox.appendChild(p1);
        textBox.appendChild(p2);
    }
    else{
        const removeElement = document.getElementById("tutorial-text");
        while(removeElement.firstChild){
            removeElement.removeChild(removeElement.firstChild);
        }
    }
});

/**
 * The play button is being set up by using the HTML id.
 * @type {HTMLElement}
 */
const playbuttonElement = document.getElementById("play_button");